Refactor to make home-manager standalone

diff --git a/apps/aarch64-darwin/build b/apps/aarch64-darwin/build
--- a/apps/aarch64-darwin/build
+++ b/apps/aarch64-darwin/build
@@ -5,23 +5,72 @@ YELLOW='\033[1;33m'
 RED='\033[1;31m'
 NC='\033[0m'
 
-if [[ $# -eq 0 ]]; then
-  echo "A host is required to properly build the flake"
-  echo "Usage: nix run '.#build' -- HOST_NAME"
-  exit 1
+HOST=""
+OTHER_ARGS=""
+
+while [ $# -gt 0 ]; do
+  case "$1" in
+    --host=*)
+      HOST="${1#*=}"
+      if [ -z "$HOST" ]; then
+        echo "${RED}Missing value for --host${NC}"
+        exit 1
+      fi
+      shift
+      ;;
+    --host)
+      if [ -z "$2" ]; then
+        echo "${RED}Missing value for --host${NC}"
+        exit 1
+      fi
+      HOST="$2"
+      shift 2
+      ;;
+    *)
+      OTHER_ARGS="$OTHER_ARGS $1"
+      shift
+      ;;
+  esac
+done
+
+if [ -n "$HOST" ]; then
+  echo "${YELLOW}Building for named host: $HOST${NC}"
+  SYSTEM=$(uname -m)
+
+  case "$SYSTEM" in
+    x86_64)
+      FLAKE_TARGET="${HOST}@x86_64-darwin"
+      ;;
+    arm64)
+      FLAKE_TARGET="${HOST}@aarch64-darwin"
+      ;;
+    *)
+      echo "${RED}Unsupported architecture: $SYSTEM${NC}"
+      exit 1
+      ;;
+  esac
+else
+  SYSTEM=$(uname -m)
+
+  case "$SYSTEM" in
+    x86_64)
+      FLAKE_TARGET="x86_64-darwin"
+      ;;
+    arm64)
+      FLAKE_TARGET="aarch64-darwin"
+      ;;
+    *)
+      echo "${RED}Unsupported architecture: $SYSTEM${NC}"
+      exit 1
+      ;;
+  esac
+  echo "${YELLOW}Building for platform: $FLAKE_TARGET${NC}"
 fi
-
-HOST=$1
-SYSTEM_TYPE="aarch64-darwin"
-FLAKE_SYSTEM="darwinConfigurations.${HOST}.system"
-
-# Shift the args so any additional ones are sent to the script
-shift 1
 
 export NIXPKGS_ALLOW_UNFREE=1
 
 echo "${YELLOW}Starting build...${NC}"
-nix --extra-experimental-features 'nix-command flakes' build .#$FLAKE_SYSTEM $@
+nix --extra-experimental-features 'nix-command flakes' build .#darwinConfigurations.$FLAKE_TARGET.system $OTHER_ARGS
 
 echo "${YELLOW}Cleaning up...${NC}"
 unlink ./result
diff --git a/apps/aarch64-darwin/build-switch b/apps/aarch64-darwin/build-switch
--- a/apps/aarch64-darwin/build-switch
+++ b/apps/aarch64-darwin/build-switch
@@ -11,10 +11,18 @@ OTHER_ARGS=""
 while [ $# -gt 0 ]; do
   case "$1" in
     --host=*)
-      HOSt="${1#*=}"
+      HOST="${1#*=}"
+      if [ -z "$HOST" ]; then
+        echo "${RED}Missing value for --host${NC}"
+        exit 1
+      fi
       shift
       ;;
     --host)
+      if [ -z "$2" ]; then
+        echo "${RED}Missing value for --host${NC}"
+        exit 1
+      fi
       HOST="$2"
       shift 2
       ;;
